name: Package Entire Repository into UnityPackage

on:
  push:
    branches:
      - main

jobs:
  package_repository:
    runs-on: ubuntu-latest
    name: Package Entire Repository
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Unity Editor
      run: |
        wget -nv https://download.unity3d.com/download_unity/2020.3.12f1/LinuxEditorInstaller/Unity.tar.xz -O Unity.tar.xz
        mkdir -p unity
        tar xf Unity.tar.xz -C unity

    - name: Install Unity dependencies
      run: sudo apt-get update && sudo apt-get install -y libglu1 libxcursor1 libxi6 libxinerama1 libxrandr2 libxss1 libxtst6

    - name: Run Unity command to create UnityPackage
      run: |
        ./unity/Unity/Editor/Unity -quit -batchmode -createProjectPackage HoyoToon.unitypackage .

    - name: Upload UnityPackage artifact
      uses: actions/upload-artifact@v2
      with:
        name: HoyoToon
        path: HoyoToon.unitypackage
